sudo: false
language: perl
matrix:
    fast_finish: true
services:
    - redis-server
perl:
    - "5.14"
before_install:
    # install prereqs
    - "cpanm Date::Utility"
    - "cpanm File::ShareDir"
    - "cpanm YAML::XS"
    - "cpanm Cache::RedisDB"
    - "cpanm Format::Util::Numbers"
    - "cpanm Math::Function::Interpolator"
    - "cpanm Math::Business::BlackScholes::Binaries"
    - "cpanm Math::Business::BlackScholes::Binaries::Greeks::Vega"
    - "cpanm Math::Business::BlackScholes::Binaries::Greeks::Delta"
    - "cpanm Test::Perl::Critic"
    - "cpanm MooseX::Singleton"
    - "git clone https://1994c85ce4f602fb682076e9a102261644fb3d19@github.com/regentmarkets/perl-Finance-Asset /tmp/perl-Finance-Asset"
    - "(cd /tmp/perl-Finance-Asset && perl Makefile.PL && make install)"
    - "git clone https://1994c85ce4f602fb682076e9a102261644fb3d19@github.com/regentmarkets/perl-Quant-Framework /tmp/perl-Quant-Framework"
    - "(cd /tmp/perl-Quant-Framework && perl Makefile.PL && make install && cpanm -n --installdeps .)"
script:
    - "perl Makefile.PL && make test"
