language: perl
sudo: required
perl:
    - "5.14.2-thr"
matrix:
    fast_finish: true
services:
    - redis-server
addons:
    postgresql: "9.3"
cache: apt
before_install:
    - git clone https://1994c85ce4f602fb682076e9a102261644fb3d19@github.com/regentmarkets/travis-scripts /tmp/travis-scripts
    - /tmp/travis-scripts/setup_ssh.sh
    - git clone git://github.com/binary-com/helpers ~/travis-perl-helpers
    - AUTHOR_TESTING=0 source ~/travis-perl-helpers/init
    - PREBUILT_REPO="git@github.com:binary-com/test-perl.git" build-perl
    - sudo mkdir -p /etc/rmg; sudo ln -s $(dirname $(which perl)) /etc/rmg/bin
    - /tmp/travis-scripts/fixHostName.sh
    - sudo mkdir -p /home/git/regentmarkets

    - /tmp/travis-scripts/clone_branch.sh regentmarkets/cpan

    - /tmp/travis-scripts/redis.sh
    - . /tmp/travis-scripts/setup_perl5lib.sh
    - cpanm -n --installdeps .

install:
    - source /tmp/travis-scripts/devbox_path.sh
    - /tmp/travis-scripts/devbox.sh *.yml
    - /tmp/travis-scripts/setup_logs.sh
    - . /tmp/travis-scripts/setup_perl5lib.sh

script:
  perl Makefile.PL && RELEASE_TESTING=1 make test

after_script:
    - /tmp/travis-scripts/wait_for_ssh.sh
