language: perl
sudo: required
perl:
    - "5.14"
matrix:
    fast_finish: true
env:
    CODECOV_TOKEN: 49470ce5-1a8e-48b1-aa3c-196af4761f4b
services:
    - redis-server
#addons:
#    postgresql: "9.3"
cache: apt
before_install:
    - git clone https://1994c85ce4f602fb682076e9a102261644fb3d19@github.com/regentmarkets/travis-scripts /tmp/travis-scripts-init
    - /tmp/travis-scripts-init/clone_branch.sh regentmarkets/travis-scripts
    - /tmp/travis-scripts/setup_ssh.sh
    #- git clone git://github.com/binary-com/helpers ~/travis-perl-helpers
    #- AUTHOR_TESTING=0 source ~/travis-perl-helpers/init
    #- PREBUILT_REPO="git@github.com:binary-com/test-perl.git" build-perl
    - sudo mkdir -p /etc/rmg; #sudo ln -s $(dirname $(which perl)) /etc/rmg/bin
    #- /tmp/travis-scripts/fixHostName.sh
    #- sudo mkdir -p /home/git/regentmarkets

    #- /tmp/travis-scripts/clone_branch.sh regentmarkets/cpan

    - /tmp/travis-scripts/redis.sh
    #- . /tmp/travis-scripts/setup_perl5lib.sh
    #- cpanm -n --installdeps .
    #- cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov
install:
    #- source /tmp/travis-scripts/devbox_path.sh
    - /tmp/travis-scripts/devbox.sh *.yml
    #- /tmp/travis-scripts/setup_logs.sh
    - cpanm --quiet --notest Dist::Zilla Dist::Zilla::App::Command::cover App::cpm Devel::Cover::Report::Codecov
    - cpm install -w 2 --mirror=http://cpan.cpantesters.org/ -g  DBIx::TransactionManager::Distributed  # fix dependencies of Finance::Asset . This line should be removed later
    - cpm install -w 2 --mirror=http://cpan.cpantesters.org/ -g $(dzil authordeps --missing)
    - cpm install -w 2 --mirror=http://cpan.cpantesters.org/  -g $(dzil listdeps --author --missing) || cpanm --quiet --notest --mirror-only --mirror https://binary:L909ZCquy8Yo6h1L@stratopan.com/binary/Binary/master $(dzil listdeps --author --missing)

script:
     - dzil smoke --release --author && dzil cover -test -report codecov && dzil xtest
after_script:
    - /tmp/travis-scripts/wait_for_ssh.sh
