sudo: false
language: perl
matrix:
    fast_finish: true
services:
    - redis-server
perl:
    - "5.14"
before_install:
    # install prereqs
    - "cpanm Date::Utility"
    - "cpanm File::ShareDir"
    - "cpanm YAML::XS"
    - "cpanm Math::Function::Interpolator"
    - "cpanm Math::Business::BlackScholes::Binaries"
    - "cpanm Math::Business::BlackScholes::Binaries::Greeks::Vega"
    - "cpanm Math::Business::BlackScholes::Binaries::Greeks::Delta"
    - "cpanm Test::Perl::Critic"
    - "cpanm MooseX::Singleton"
    - "git clone https://d34c443afcc0c115c07590c76f7e3886190b3a76@github.com/regentmarkets/perl-Finance-Asset /tmp/perl-Finance-Asset"
    - "(cd /tmp/perl-Finance-Asset && perl Makefile.PL && make install)"
script:
    - "perl Makefile.PL && make test"
