dist: precise
group: deprecated-2017Q1
language: perl
sudo: required
perl:
    - "5.26"
matrix:
    fast_finish: true
env:
    CODECOV_TOKEN: 49470ce5-1a8e-48b1-aa3c-196af4761f4b
services:
    - redis-server
cache: apt
before_install:
    - git clone ssh://git@github.com/regentmarkets/travis-scripts /tmp/travis-scripts-init
    - /tmp/travis-scripts-init/clone_branch.sh regentmarkets/travis-scripts
    - /tmp/travis-scripts/setup_ssh.sh
    - sudo mkdir -p /etc/rmg /home/git/binary-com
    - . /tmp/travis-scripts/setup_perl.sh
    - /tmp/travis-scripts/redis.sh
install:
    - /tmp/travis-scripts/devbox.sh *.yml
    - . /tmp/travis-scripts/perl_cpan.sh

script:
     - /etc/rmg/bin/perl -e 'print "$^V\n"'; which perl; ls -l /etc/rmg/bin
     - dzil smoke --release --author && dzil cover -test -report codecov && dzil xtest
after_script:
    - /tmp/travis-scripts/wait_for_ssh.sh
