jobs:
  build:
    docker:
    - auth:
        password: $DOCKERHUB_PASSWORD
        username: circle4regentmarkets
      image: regentmarkets/debian-ci:stable
      user: nobody
    steps:
    - add_ssh_keys:
        fingerprints:
        - 85:5e:13:f8:60:b2:55:a1:df:d1:8e:77:17:4c:3b:2d
    - run:
        command: /opt/circle/prepare-test.sh
        name: Update git repositories
    - run:
        command: |
          source /etc/profile.d/perl5.sh
          dzil smoke --release --author && dzil cover -test && dzil xtest
        name: Run test
    shell: /bin/bash -leo pipefail
    working_directory: /home/git/regentmarkets/perl-Pricing-Engine-European-Digital-Slope
version: 2
workflows:
  build-workflow:
    jobs: &1
    - build:
        context: perl
  daily:
    jobs: *1
    triggers:
    - schedule:
        cron: 2 20 * * *
        filters:
          branches:
            only:
            - master
  tagged:
    jobs:
    - build:
        context: perl
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^V\d+_.*/
  version: 2
