name: Daily master test
run-name: Daily test on master branch
on:
  schedule:
    - cron: '2 20 * * *'
jobs:
  build: 
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.DEBIAN_CI }}
      credentials:
        username: circle4regentmarkets
        password: ${{ secrets.DOCKER_PASSWORD }}
      options: --user nobody:nogroup
    defaults:
      run:
        shell: bash -le {0}
    steps:
      - name: setup CI step
        uses: regentmarkets/github-actions/ci-setup@perl
        with:
          read_github_ssh_key: ${{ secrets.READ_GITHUB_SSH_KEY }}
          need_service: false
          repository: ${{ github.repository }}
      - name : Run Tests 
        run: |
          source /etc/profile.d/perl5.sh
          dzil smoke --release --author && dzil cover -test && dzil xtest
        working-directory: /home/git/${{ github.repository }}
